apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo-demo
  namespace: flux-system
spec:
  interval: 10s
  ref:
    branch: master
  url: https://github.com/cykbls01/podinfo-demo.git 
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-demo
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./charts/podinfo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: podinfo-demo
  interval: 10s
  targetNamespace: default
